Update NodeJS Image Version
Without this update the docker build fails at step:

$ webpack build
internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/home/node_modules/colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (/home/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/node_modules/webpack-cli/lib/webpack-cli.js:10:66)
    at Module._compile (/home/node_modules/v8-compile-cache/v8-compile-cache.js:192:30) {
  code: 'MODULE_NOT_FOUND'
}
error Command failed with exit code 1.

It succeded when I updated to the 14.5 version.

https://github.com/facebook/create-react-app/issues/9273